### ISSUE TITLE
TypeError after npm update

### ISSUE THREAD

**Issue by ainawing** [coolchip/node-red-contrib-luxtronik2#2]
Hiho,

I use iobroker, which requested an npm update to a specific version. Everything worked fine for several months prior to the update, so I know that the pump and its firmware are compatible. I'm kinda stumped, so maybe you can shed some light on this.

node-red-contrib-luxtronik2: 0.4.0

after failing I ran this using the command line:
`sudo nodejs --max-old-space-size=128 /opt/iobroker/node_modules/node-red/red.js -v --settings /opt/iobroker/iobroker-data/node-red/settings.js`

command line output:
```
9 Jul 18:48:18 - [info] Node-RED Version: v1.1.0
9 Jul 18:48:18 - [info] Node.js  Version: v10.21.0
9 Jul 18:48:18 - [info] Linux 4.19.0-6-amd64 x64 LE
9 Jul 18:48:21 - [info] Paletten-Nodes werden geladen
9 Jul 18:48:24 - [info] Polymer started at /polymer
9 Jul 18:48:26 - [info] Dashboard version 2.22.1 started at /ui
9 Jul 18:48:27 - [info] Einstellungsdatei: /opt/iobroker/iobroker-data/node-red/settings.js
9 Jul 18:48:27 - [info] Kontextspeicher: 'default' [ module=memory]
9 Jul 18:48:27 - [info] Benutzerverzeichnis: /opt/iobroker/iobroker-data/node-red/
9 Jul 18:48:27 - [warn] Projekte inaktiviert: editorTheme.projects.enabled=false
9 Jul 18:48:27 - [info] Flow-Datei: /opt/iobroker/iobroker-data/node-red/flows.json
9 Jul 18:48:27 - [info] Flows starten
9 Jul 18:48:29 - [info] Flows gestartet
9 Jul 18:48:29 - [info] Server wird jetzt auf http://127.0.0.1:1880/ ausgeführt.
9 Jul 18:48:37 - [info] [inject:230c0f43.a4e328] Wiederholen = 60000
9 Jul 18:48:37 - [red] Uncaught Exception:
9 Jul 18:48:37 - TypeError: Cannot read property '0' of undefined
    at /opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-luxtronik2-ws/luxtronik2-ws.js:75:49
    at Parser.<anonymous> (/opt/iobroker/iobroker-data/node-red/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:198:13)
    at SAXParser.onclosetag (/opt/iobroker/iobroker-data/node-red/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/opt/iobroker/iobroker-data/node-red/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/opt/iobroker/iobroker-data/node-red/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/opt/iobroker/iobroker-data/node-red/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/opt/iobroker/iobroker-data/node-red/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/opt/iobroker/iobroker-data/node-red/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/opt/iobroker/iobroker-data/node-red/node_modules/xml2js/lib/parser.js:5:59)
```

Thank you for your help. If there are any questions or you want me to run a few tests, feel free. I just hope email notifications work properly ;)

**Comment by coolchip** [comment]
I'm the maintainer of node-red-contrib-luxtronik2. The error you show me is from node-red-contrib-luxtronik2-ws. Please ask here:
https://github.com/bouni/node-red-contrib-luxtronik2-ws
