### ISSUE TITLE
Cannot read property 'end' of null

### ISSUE THREAD

**Issue by hpsopanen** [coolchip/node-red-contrib-luxtronik2#7]
3 Oct 13:01:04 - [red] Uncaught Exception:
3 Oct 13:01:04 - TypeError: Cannot read property 'end' of null
    at Luxtronik.<anonymous> (/home/pi/.node-red/node_modules/luxtronik2/luxtronik.js:452:21)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Unit entered failed state.
nodered.service: Failed with result 'exit-code'.
nodered.service: Service hold-off time over, scheduling restart.

**Comment by coolchip** [comment]
Sorry, I've no idea. Did you get this often or only sometimes?

**Comment by hpsopanen** [comment]
It appeared a few times a day.
The fault disappeared when I updated the heat pump software.
